#!/bin/bash

set -ex

# Set tokyo-stack overrides, if not already set.
[[ -z "$GATEWAY" ]] && export GATEWAY="10.230.56.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.230.58.0/21"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.230.58.50:10.230.58.254"
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.230.56.2"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="172.16.0.0/12"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.230.19.26"

export BARE_METAL="True"
./profiles/default $1 $2 $3 $4 $5

